# Generated by Django 4.2.2 on 2023-07-09 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy_app', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 15, 0, 14, 678051, tzinfo=datetime.timezone.utc)),
        ),
    ]
