# Generated by Django 4.2.2 on 2023-07-09 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy_app', '0007_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 16, 20, 12, 133977, tzinfo=datetime.timezone.utc)),
        ),
    ]
